# Generated by Django 3.2.25 on 2025-06-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='texto',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='hora_creacion',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
