# Generated by Django 3.2.25 on 2025-06-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250622_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='opinion_personal',
            field=models.TextField(blank=True, default='Sin opinión'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, default='Sin opinión', upload_to='portadas/'),
            preserve_default=False,
        ),
    ]
