# Generated by Django 3.2.25 on 2025-06-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20250622_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='calificacion',
            new_name='estrellas',
        ),
        migrations.AlterField(
            model_name='libro',
            name='opinion_personal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
